update nf-core patches

diff --git a/modules/nf-core/mitohifi/findmitoreference/mitohifi-findmitoreference.diff b/modules/nf-core/mitohifi/findmitoreference/mitohifi-findmitoreference.diff
--- a/modules/nf-core/mitohifi/findmitoreference/mitohifi-findmitoreference.diff
+++ b/modules/nf-core/mitohifi/findmitoreference/mitohifi-findmitoreference.diff
@@ -19,35 +19,29 @@ Changes in 'mitohifi/findmitoreference/main.nf':
  
      when:
      task.ext.when == null || task.ext.when
-@@ -19,15 +19,28 @@
+@@ -19,10 +19,22 @@
      script:
      def args = task.ext.args ?: ''
      """
++    # override workflow exit on findMitoReference.py error (issues: #277, #171, #220)
 +    set +e
      findMitoReference.py \\
          --species "$species" \\
          --outfolder . \\
          $args
 +    set -e
++
++    # Test: for success either both or neither output found, fail if only one found
++
++    FASTA=\$(find . -maxdepth 1 -name "*.fasta" -type f | wc -l)
++    GB=\$(find . -maxdepth 1 -name "*.gb" -type f | wc -l)
++
++    if [[ \$FASTA -ne \$GB ]]; then
++        exit 1
++    fi
  
      cat <<-END_VERSIONS > versions.yml
      "${task.process}":
-         mitohifi: \$( mitohifi.py -v | sed 's/.* //' )
-     END_VERSIONS
-+
-+    # Test: task success if both, or no outputs are found, and fail upon partial output (one of two filetypes found)
-+
-+    FASTA_COUNT=\$(ls *.fasta 2>/dev/null | wc -l)
-+    GB_COUNT=\$(ls *.gb 2>/dev/null | wc -l)
-+
-+    if [[ \$FASTA_COUNT -eq \$GB_COUNT ]]; then
-+        exit 0
-+    else
-+        exit 1
-+    fi
-     """
- 
-     stub:
 
 'modules/nf-core/mitohifi/findmitoreference/environment.yml' is unchanged
 'modules/nf-core/mitohifi/findmitoreference/meta.yml' is unchanged
